### ISSUE TITLE
"cannot parse list: a list converter must be specified"

### ISSUE THREAD

**Issue by dkmonaghan** [emc-openstack/storops#337] opened 2021-01-04 22:21 UTC
Hello,

We are receiving the following output:

```
cannot parse list: [{'currentTransferSize': 0, 'currentTransferRemain': 0, 'dstStatus': 0, 'name': 'sv_27=>sv_27', 'networkStatus': 0, 'currentWriteRate': 0, 'dstLunInstanceId': 'root/emc:EMC_UEM_ReplicationRemoteSystemLeaf%InstanceID=RS_1%Name=XXXXXX%SystemName=VNXe*root/emc:EMC_UEM_StorageVolumeLeaf%InstanceID=sv_27', 'currentTransferEstRemainTime': 0, 'srcLunId': 'sv_27', 'currentTransferRate': 0, 'srcLunInstanceId': 'root/emc:EMC_UEM_StorageVolumeLeaf%InstanceID=sv_27', 'currentReadRate': 0, 'srcStatus': 3, 'dstLunId': 'sv_27', 'maxTimeOutOfSync': 0}, {'currentTransferSize': 0, 'currentTransferRemain': 0, 'dstStatus': 0, 'name': 'sv_25=>sv_25', 'networkStatus': 0, 'currentWriteRate': 0, 'dstLunInstanceId': 'root/emc:EMC_UEM_ReplicationRemoteSystemLeaf%InstanceID=RS_1%Name=XXXXXX%SystemName=VNXe*root/emc:EMC_UEM_StorageVolumeLeaf%InstanceID=sv_25', 'currentTransferEstRemainTime': 0, 'srcLunId': 'sv_25', 'currentTransferRate': 0, 'srcLunInstanceId': 'root/emc:EMC_UEM_StorageVolumeLeaf%InstanceID=sv_25', 'currentReadRate': 0, 'srcStatus': 3, 'dstLunId': 'sv_25', 'maxTimeOutOfSync': 0}, {'currentTransferSize': 0, 'currentTransferRemain': 0, 'dstStatus': 0, 'name': 'sv_26=>sv_26', 'networkStatus': 0, 'currentWriteRate': 0, 'dstLunInstanceId': 'root/emc:EMC_UEM_ReplicationRemoteSystemLeaf%InstanceID=RS_1%Name=XXXXXX%SystemName=VNXe*root/emc:EMC_UEM_StorageVolumeLeaf%InstanceID=sv_26', 'currentTransferEstRemainTime': 0, 'srcLunId': 'sv_26', 'currentTransferRate': 0, 'srcLunInstanceId': 'root/emc:EMC_UEM_StorageVolumeLeaf%InstanceID=sv_26', 'currentReadRate': 0, 'srcStatus': 3, 'dstLunId': 'sv_26', 'maxTimeOutOfSync': 0}].  a list converter must be specified.
```

When running the following code against our Unity 400 appliances:

```
# Loop through replication sessions
filters={
    'local_role': storops.ReplicationSessionReplicationRoleEnum.SOURCE,
    'status': storops.ReplicationOpStatusEnum.PAUSED
}
for session in unity.get_replication_session(**filters):

    # As we're resuming NAS servers, we don't need to resume any filesystems - they get done automatically
    if session.replication_resource_type == storops.ReplicationEndpointResourceTypeEnum.FILESYSTEM:
        continue

    session.resume()
```

This code just loops through all replication sessions and runs `session.resume()`. The code works as expected, resuming all sessions, but the above output gets sent to stdout. Is there any way to fix / suppress this output?

**Comment by yong-huang** [comment] 2021-01-26 09:14
Hi,

I cannot reproduce this issue in my test environment (Unity 500, 5.1.0), this is my test script:

```python
import storops

# storops.enable_log()

unity = storops.UnitySystem('xxx', 'xxx', 'xxx')

filters = {
    'local_role': storops.ReplicationSessionReplicationRoleEnum.SOURCE,
    # 'status': storops.ReplicationOpStatusEnum.AUTO_SYNC_CONFIGURED,
    'status': storops.ReplicationOpStatusEnum.PAUSED,
}

for session in unity.get_replication_session(**filters):
    # if session.replication_resource_type == storops.ReplicationEndpointResourceTypeEnum.FILESYSTEM:
    if not session.replication_resource_type == storops.ReplicationEndpointResourceTypeEnum.NASSERVER:
        continue

    # print(session)
    session.resume()
```

The script executed successfully. No "cannot parse list" error as you mentioned.
What's the software version of your Unity?
Maybe it is a Unity issue or compatibility issue of a specific Unity version and the latest storops?

**Comment by dkmonaghan** [comment] 2021-02-01 19:32
Hi @yong-huang,

I've used this code of ours again this evening and have the same issue with "cannot parse list".

Here is some more information:

- Tested on both Unity version 5.0.4.0.5.012 and 5.0.6.0.6.234
- Python version 3.5.3
- storops version 1.2.8

**Comment by yong-huang** [comment] 2022-03-17 06:44
Fixed in https://github.com/emc-openstack/storops/pull/363.

**Closed** 2022-03-17 08:09 UTC
Labels: bug
