### ISSUE TITLE
Name of VNX Storage 

### ISSUE THREAD

**Issue by sunnyrarora** [emc-openstack/storops#25] opened 2016-09-21 21:25 UTC
Hi Team,
From the VNX Dashboard, we can view Name and other details  assigned to the Storage box.    
![sysinfo](https://cloud.githubusercontent.com/assets/13348767/18729495/a26f74ec-806f-11e6-9545-662fd284d4fe.PNG)

How can we view the same in storops

Thanks
Sunny

**Comment by jealous** [comment] 2016-09-22 03:31
Hi Sunny,

You should be able to get it with the serial or the name property of `VNXSystem`.
``` python
vnx = VNXSystem('<ip>', '<user>', '<password>')
vnx.serial # serial number
vnx.name # sp name
vnx.model # model
```

**Comment by sunnyrarora** [comment] 2016-09-22 10:50
Hi Jealous,
Thanks for the reply. Below is the ouput, name of VNX is not K10.But I am looking for Particular Hostname assigned to Storage. 
```
>>> vnx.name
u'K10'
>>> vnx.serial
u'XXX001XXXXXX'
>>> vnx.model
u'VNX8000'

```
Thanks
Sunny

**Comment by jealous** [comment] 2016-09-22 10:56
Hi Sunny,

I think I find a way to retrieve it.  It was not implemented yet.  Let me work on a new version to fix this.

**Comment by jealous** [comment] 2016-09-23 06:22
Hi Sunny,

The issue is fixed.  Now you could use `system.name` to retrieve the name of VNX storage.
You could also use following syntax to modify the name:
``` python
system.name = 'new_name'
```

**Comment by jealous** [comment] 2016-09-23 10:41
Hi Sunny,

vnx.name should return the systum name.  Could you check whether the ip and credential is correct?
You could try other method and see if they return proper results.
If it still does not work, please open the debug level log and paste it here.  Thanks.

**Comment by sunnyrarora** [comment] 2016-09-23 11:20
Hi Jealous,
IP, Username and password are correct 
```
>>>from storops import VNXSystem
>>>import logging
>>>logging.basicConfig(level=logging.DEBUG)
```
Then below command runs with all the output showing each and every operation and displays the last output which ihad  shown below
```
>>>>>vnx = VNXSystem('10.xx.xx.xx', 'user', 'password' )
.
.
.
{
    "VNXSystem": {
        "agent_rev": "7.33.9 (1.55)",
        "existed": true,
        "hash": 334XXXX,
        "model": "VNX8000",
        "model_type": "Rackmount",
        "revision": "05.XX.00X.X.XXX",
        "serial": "APM0XXXXXXXX"
    }
}
```
Then i try to print vnx.name, strangely no ouput for it. Rest commands works fine.
```
>>> vnx.name
>>>
```
Any other way to check vnx.name or to pull out logs for it ?
P.S : I am using Read-only user account of vnx box, which works well for the other storops  commands where we dont need to modigy things.

Thanks
Sunny

**Comment by jealous** [comment] 2016-09-23 12:01
Hi Sunny,

It uses following command to retrieve the array name.
`naviseccli.exe -h 10.XX.XX.XX -user user -password *** -scope 0 arrayname`
You could try this command and see what's the output.  My suspect is that you are using a VNX that doesn't support this command...  
Please have a try and let me know the result.  Thanks!

**Comment by jealous** [comment] 2016-09-23 12:21
Some more information.  It works on my test array.  Here is how it looks like:
``` python
In [1]: from storops import VNXSystem

In [2]: vnx = VNXSystem('10.xx.xx.xx')

In [3]: vnx.name
Out[3]: 'APMxxxxxxxxxxx'

In [4]: vnx
Out[4]:
{
    "VNXSystem": {
        "agent_rev": "7.33.9 (1.55)",
        "existed": true,
        "hash": 6562873,
        "model": "VNX5800",
        "model_type": "Rackmount",
        "name": "APMxxxxxxxxxxx",
        "revision": "05.33.009.5.155",
        "serial": "APMxxxxxxxxxxx"
    }
}
```

**Comment by sunnyrarora** [comment] 2016-09-23 12:37
Thanks Jealous for the detailed approach.

But as i said, It seems privilege issue, even command i tried 
```
C:\Program Files (x86)\EMC\Navisphere CLI>naviseccli.exe -h 10.xx.xx.xx -user
discovery_user -password password -scope 0 arrayname
Error returned from the Management Server on 10.xx.xx.xx.
User ' Navi User user' has been denied access to this operation because of security role privilege violation.
```
But, Then I tried with Admin user and it Displayed the Output.
```
C:\Python27>naviseccli.exe -h 10.xx.xx.xx -user Admin -password **** -scope 0 arrayname
Array Name:  PHLXXXXXXXXXX
```

Anything done on the perspective of readonly user to get the same output. Because read only user when able to get all the details then i think it should be able to fetch the Array name.

Thanks again
Regards

Sunny

**Comment by jealous** [comment] 2016-09-23 13:51
Hi Sunny,

Unfortunately, I don't think we could retrieve this information from other commands.  Looks like the `arrayname` command is designed to satisfy this requirement.  But certainly it doesn't make sense to require admin privilege for a get operation.
I guess what I could do is to file a bug about this issue but I don't think we still fix this kind of issue on VNX.

**Comment by jealous** [comment] 2016-09-29 05:38
Hi Sunny,

I have filed a bug report at VNX.  I am closing this issue.  Please let me know if you have more questions.

**Closed by jealous** 2016-09-29 05:38 UTC
Labels: question, VNX
